location_render:
    pattern:  /location/{id}
    defaults: { _controller: ACInst3LocationBundle:Location:render }

location_list:
    pattern:  /location/list/{map}.{_format}
    defaults: { _controller: ACInst3LocationBundle:Location:list, map: false, _format: html }
    requirements:
        _format:  html|json
map_render:
    pattern:  /map/{id}
    defaults: { _controller: ACInst3LocationBundle:Map:render }