parameters:
#    ac_inst3_location.example.class: AltCloud\Instance3LocationBundle\Example

services:
#    ac_inst3_location.example:
#        class: %ac_inst3_location.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
