admin_location:
    pattern:  /
    defaults: { _controller: "ACInst3LocationBundle:Location:index" }

admin_location_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACInst3LocationBundle:Location:show" }

admin_location_new:
    pattern:  /new
    defaults: { _controller: "ACInst3LocationBundle:Location:new" }

admin_location_create:
    pattern:  /create
    defaults: { _controller: "ACInst3LocationBundle:Location:create" }
    requirements: { _method: post }

admin_location_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACInst3LocationBundle:Location:edit" }

admin_location_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACInst3LocationBundle:Location:update" }
    requirements: { _method: post }

admin_location_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACInst3LocationBundle:Location:delete" }
    requirements: { _method: post }
